package rules
import java.util.Map;
import java.util.HashMap;
rule scoreCheck1
     dialect "mvel"
     when 
         resultMap : HashMap() 
         map: Map(this["score"]>=60)
     then
     resultMap.put("userNameCn",map.get("userNameCn"));
     resultMap.put("message","及格");
end
rule scoreCheck2
     dialect "mvel"
         when
             resultMap : HashMap() 
             map: Map(this["score"]<60)
         then
         resultMap.put("userNameCn",map.get("userNameCn"));
         resultMap.put("message","不及格");
end